services:
  bot:
    restart: unless-stopped
    image: ghcr.io/tbmpqf/tbm_cpu_v2:${COMMIT_REF:-main}
    container_name: tbm-cpu-v2
    hostname: tbm-cpu-v2
    environment:
      APEX_API: ${APEX_API:?required}
      BDD_URL: ${BDD_URL:?required}
      GENIUS_API: ${GENIUS_API:?required}
      MINECRAFT_SERVER_URL: ${MINECRAFT_SERVER_URL:?required}
      TOKEN: ${TOKEN:?required}
      TWITCH_ID: ${TWITCH_ID:?required}
      TWITCH_SECRET: ${TWITCH_SECRET:?required}
      TZ: Europe/Paris
