const messagesRandom = {

    bump: [
    `📢丨𝐔n bump de <USER_MENTION> ! 𝐌ême les dieux du bump applaudissent ! - 🙌`,
    `📢丨𝐒coop : <USER_MENTION> vient de bump. 𝐂NN est déjà sur le coup ! - 📺`,
    `📢丨𝐔n bump explosif par <USER_MENTION> ! 𝐌ichael Bay veut en faire un film ! - 💥`,
    `📢丨𝐌erci <USER_MENTION> pour ce bump légendaire. 𝐌ême Gandalf est impressionné ! - 🧙‍♂️`,
    `📢丨𝐔n bump intergalactique signé <USER_MENTION> ! 𝐄lon Musk prend des notes. - 🚀`,
    `📢丨𝐌erci <USER_MENTION> pour ce bump ! 𝐌ême nos bots sont émus. - 🤖`,
    `📢丨𝐔n bump si épique que Netflix veut en faire une série ! 𝐌erci <USER_MENTION> ! - 🎥`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐓u viens de sauver la galaxie avec ce bump ! - 🌌`,
    `📢丨𝐔n bump de <USER_MENTION> ! 𝐋es aliens nous ont repérés grâce à toi ! - 👽`,
    `📢丨𝐁ump de haute voltige signé <USER_MENTION> ! 𝐎n te donne une médaille d’or. - 🥇`,
    `📢丨𝐌erci <USER_MENTION> pour ce bump ! 𝐋a légende dit que Chuck Norris l’a validé. - 🥋`,
    `📢丨𝐔n bump royal par <USER_MENTION> ! 𝐋es chevaliers du serveur sont en fête ! - 🤴`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump a illuminé le serveur comme jamais ! - 💡`,
    `📢丨𝐕oici un bump signé <USER_MENTION> ! 𝐌ême la NASA est impressionnée. - 🚀`,
    `📢丨𝐌erci pour ce bump spectaculaire, <USER_MENTION> ! 𝐓'es notre super-héros ! - 🦸‍♂️`,
    `📢丨𝐔n bump signé <USER_MENTION> ! 𝐌ême les chats du serveur miaulent de joie. - 🐱`,
    `📢丨𝐌erci <USER_MENTION> pour ce bump ! 𝐎n te doit une pizza galactique. - 🍕`,
    `📢丨𝐔n bump si puissant que même Thanos en a lâché le gant ! 𝐌erci <USER_MENTION> ! - 🦾`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump vient de déclencher une éclipse solaire ! - 🌒`,
    `📢丨𝐔n bump tellement incroyable que les pandas nous envoient leurs félicitations. 𝐌erci <USER_MENTION> ! - 🐼`,
    `📢丨𝐁ump validé par <USER_MENTION> ! 𝐋a timeline vient d’exploser. - 💥`,
    `📢丨𝐔n bump signé <USER_MENTION> ! 𝐋e serveur vient de prendre +10 en charisme. - 😎`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump a réveillé les admins endormis. - 😴➡️😳`,
    `📢丨𝐔n bump d’élite par <USER_MENTION> ! 𝐄ncore plus propre qu’un speedrun. - ⏱️`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐌ême le bouton "Like" a tremblé. - 👍`,
    `📢丨𝐔n bump critique par <USER_MENTION> ! 𝐗P x3, loot légendaire ! - 💎`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump est certifié sans bug (normalement). - 🐛❌`,
    `📢丨𝐔n bump signé <USER_MENTION> ! 𝐋a hype est officiellement relancée. - 🔥`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump mérite un GG collectif. - 👏`,
    `📢丨𝐔n bump si propre que même Stack Overflow approuve. - 🧠`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump est entré dans les annales du serveur. - 📜`,
    `📢丨𝐔n bump par <USER_MENTION> ! 𝐋a RNG est clairement de ton côté aujourd’hui. - 🎲`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump a fait ping tout l’univers. - 📡`,
    `📢丨𝐔n bump de compétition par <USER_MENTION> ! 𝐋es tryharders sont fiers. - 🏆`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump est validé par le conseil des sages. - 🧙`,
    `📢丨𝐔n bump signé <USER_MENTION> ! 𝐋a prod est lancée, aucun retour arrière. - 🚧`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump a traversé l’espace-temps. - 🕒`,
    `📢丨𝐔n bump tellement clean qu’il brille. 𝐌erci <USER_MENTION> ! - ✨`,
    `📢丨𝐌erci <USER_MENTION> ! 𝐂e bump a réveillé la nostalgie des anciens. - 🕹️`,
    `📢丨𝐔n bump masterclass par <USER_MENTION> ! 𝐎n applaudit debout. - 👏🔥`,
    ],

    rolesMenu: [
        `🌟 ◟𝐂hoisis tes rôles et débloque l'accès aux salons réservés pour papoter avec la communauté passionnée de ton jeu préféré ! 🎮\n\n🔥 ◟𝐐ue tu sois là pour échanger des stratégies, partager tes exploits ou simplement pour rigoler avec d'autres gamers, cet endroit est fait pour toi ! 𝐄t si l'envie de changer de jeu te prend, pas de souci : tu peux modifier tes rôles à tout moment.\n\n **𝐑ejoins-nous**, amuse-toi, et plonge dans un océan de fun et d'amitié ! 𝐏rêt à faire partie de cette légende ? 𝐂'est parti, à toi de jouer ! ✨`,
        `🎊 ◟𝐓u es à un clic de l'aventure ! Choisis tes rôles et ouvre les portes des salons où les passionnés de ton jeu se réunissent ! 🎮\n\n🔥 ◟𝐓u peux discuter de stratégies, partager tes réussites, ou juste t'amuser avec d'autres gamers ! 𝐄t si un autre jeu t'appelle, change tes rôles sans hésiter !\n\n **𝐑ejoins-nous**, amuse-toi, et fais partie de cette communauté incroyable ! 𝐏rêt à te lancer ? 𝐂'est à toi de jouer ! ✨`,
        `🎮 ◟𝐂'est le moment de briller ! Choisis tes rôles et accède aux salons réservés où les fans de ton jeu se retrouvent ! 🌟\n\n🔥 ◟𝐔ne multitude de discussions t'attendent, que ce soit pour échanger des conseils ou juste pour passer un bon moment ! 𝐄t si l'envie d'explorer un autre jeu te prend, adapte tes rôles à ta guise.\n\n **𝐑ejoins-nous**, amuse-toi, et plonge dans l'univers du gaming ! 𝐏rêt à écrire ta propre légende ? 𝐂'est parti, à toi de jouer ! ✨`,
        `✨ ◟𝐍e manque plus qu'une chose : tes rôles ! Choisis-les pour accéder aux salons où se trouve la communauté de ton jeu préféré ! 🎮\n\n🔥 ◟𝐂e lieu est parfait pour échanger des stratégies, partager tes exploits, ou juste rigoler avec d'autres gamers ! 𝐄t si un nouveau défi te tente, change tes rôles à tout moment.\n\n **𝐑ejoins-nous**, amuse-toi, et plonge dans un océan de fun ! 𝐏rêt à faire partie de cette grande aventure ? 𝐂'est le moment de te lancer ! 💥`,
        `💬 ◟𝐒électionne tes rôles et débloque des salons exclusifs pour discuter avec d'autres passionnés de ton jeu ! 🎮\n\n🔥 ◟𝐓u peux échanger des astuces, partager tes victoires ou juste profiter d'un bon moment ensemble ! 𝐄t si tu veux changer d'univers, modifie tes rôles comme bon te semble.\n\n **𝐑ejoins-nous**, éclate-toi, et fais partie de cette communauté dynamique ! 𝐏rêt à vivre cette aventure ? 𝐂'est à toi de jouer ! ✨`,
        `🚀 ◟**𝐄mbarque pour une nouvelle quête !** 𝐂hoisis tes rôles pour accéder aux salons exclusifs et connecter avec la communauté de ton jeu adoré ! 🎮\n\n🌟 ◟Que tu sois ici pour partager des astuces, célébrer tes victoires ou juste t'amuser, cet endroit est fait pour toi ! 𝐄t si l'appel d'un autre jeu se fait sentir, pas de souci : change tes rôles quand tu veux.\n\n**𝐑ejoins-nous**, éclate-toi, et plonges dans un océan de fun et d'amitié ! 𝐏rêt à faire partie de cette aventure incroyable ? 𝐂'est le moment de briller ! ✨`,
        `🎉 ◟**𝐋a fête commence ici !** 𝐂hoisis tes rôles pour accéder aux salons réservés et te connecter avec les fans de ton jeu préféré ! 🎮\n\n🎊 ◟Que tu sois là pour échanger des conseils, partager tes succès ou juste pour rire, cet endroit est fait pour toi ! 𝐄t si l'envie d'un autre jeu te prend, pas de problème : modifie tes rôles à ta guise.\n\n**𝐑ejoins-nous**, amuse-toi, et plonge dans un océan de bonne humeur et d'amitié ! 𝐏rêt à rejoindre la légende ? 𝐂'est parti, à toi de jouer ! ✨`,
        `🌈 ◟**𝐋'aventure t'attend !** 𝐂hoisis tes rôles pour débloquer l'accès aux salons dédiés et interagir avec la communauté de ton jeu favori ! 🎮\n\n💪 ◟Que tu souhaites échanger des stratégies, partager tes succès ou simplement t'amuser, cet espace est pour toi ! 𝐄t si tu veux changer de jeu, aucun souci : adapte tes rôles à tout moment.\n\n**𝐑ejoins-nous**, amuse-toi, et plonge dans un monde de fun et d'amitié ! 𝐏rêt à faire partie de cette grande aventure ? 𝐂'est le moment de briller ! 💥`
    ],

    DailyStreak: [
        `𝐀ttention, **<USER_NAME>** vient d'atteindre \`<STREAK>\` jours consécutifs de bonus quotidien ! 💥 𝐏eut-on l'arrêter ?!`,
        `**<USER_NAME>** a enchaîné \`<STREAK>\` jours d'affilée ! 𝐎n dirait qu'il ou elle ne dort jamais ! 🛌`,
        `𝐀vec \`<STREAK>\` jours consécutifs, **<USER_NAME>** est devenu un maître du daily bonus ! 🏆`,
        `𝐎h là là ! **<USER_NAME>** a survécu \`<STREAK>\` jours sans oublier son bonus quotidien ! 𝐑espect ! 🙌`,
        `𝐄st-ce un robot ? 𝐍on, c'est juste **<USER_NAME>** qui a atteint \`<STREAK>\` jours de streak !`,
        `\`<STREAK>\` jours consécutifs de daily bonus pour **<USER_NAME>** ! 𝐁ientôt une statue à son effigie dans le serveur ! 🗿`,
        `**<USER_NAME>** est en feu avec \`<STREAK>\` jours consécutifs de daily bonus ! 🔥 𝐎n ne peut plus l'arrêter !`,
        `𝐖oah ! **<USER_NAME>** a maintenant \`<STREAK>\` jours de streak ! 𝐅aut-il lui décerner un prix ? 🏅`,
        `𝐈ncroyable ! **<USER_NAME>** a maintenu sa streak pendant \`<STREAK>\` jours ! 𝐔n vrai pro de la discipline ! 👏`,
        `\`<STREAK>\` jours sans faute pour **<USER_NAME>** ! 𝐋a persévérance au niveau légendaire ! 🐉`,
        `𝐒alut, légende ! **<USER_NAME>** en est à \`<STREAK>\` jours de suite ! 𝐀 quand une biographie ? 📖`,
        `**<USER_NAME>** a atteint \`<STREAK>\` jours d'affilée ! 𝐌ême le soleil est impressionné ! ☀️`,
        `𝐌éga respect à **<USER_NAME>** pour ses \`<STREAK>\` jours de suite ! 𝐎n va devoir créer une salle des champions ! 🏆`,
        `**<USER_NAME>** et ses \`<STREAK>\` jours de streak sont devenus une légende vivante ! 🤩`,
        `**<USER_NAME>** cumule déjà \`<STREAK>\` jours ! 𝐈l doit avoir un rappel dans son agenda ! 📅`,
        `\`<STREAK>\` jours de suite pour **<USER_NAME>** ! 𝐁ientôt on lui donne les clés du serveur ! 🔑`,
        `**<USER_NAME>** a fait son daily bonus pendant \`<STREAK>\` jours d'affilée ! 𝐕a-t-il battre le record du monde ? 🌍`,
        `𝐄n mode machine ! **<USER_NAME>** a atteint \`<STREAK>\` jours sans oublier le bonus ! 🤖`,
        `𝐏arfait, parfait, parfait ! **<USER_NAME>** enchaîne \`<STREAK>\` jours de bonus ! 𝐐ui dit mieux ? 🌟`,
        `𝐖oah, avec \`<STREAK>\` jours, **<USER_NAME>** est devenu l'empereur du streak ! 👑`,
        `\`<STREAK>\` jours ?! 𝐀 ce rythme, **<USER_NAME>** va finir par percer le secret de l'éternité ! ⏳`,
        `**<USER_NAME>** a survécu \`<STREAK>\` jours sans faille ! 𝐋e monde des streaks s'incline ! 🕹️`,
        `\`<STREAK>\` jours consécutifs pour **<USER_NAME>** ! 𝐕a falloir une médaille en platine ! 💿`,
        `**<USER_NAME>** est passé maître du streak avec \`<STREAK>\` jours ! 𝐏rochain objectif : l'infini ! ♾️`,
        `𝐎n a atteint le niveau “Streak Master” ! **<USER_NAME>** est à \`<STREAK>\` jours d'affilée ! 🙏`,
        `**<USER_NAME>** a validé \`<STREAK>\` jours de suite ! 𝐋a régularité, c'est son deuxième prénom ! 📆`,
        `**<USER_NAME>** 𝐕ient de valider \`<STREAK>\` jours ! 𝐋a courbe de régularité est parfaite. - 📊`,
        `\`<STREAK>\` jours consécutifs pour **<USER_NAME>** ! 𝐋a discipline est officiellement maîtrisée. - 🧘`,
        `**<USER_NAME>** débloque le succès “𝐂onnexion Quotidienne” niveau \`<STREAK>\` ! - 🎮`,
        `**<USER_NAME>** et son réveil interne n’ont jamais failli depuis \`<STREAK>\` jours. - ⏳`,
        `𝐒treak de \`<STREAK>\` jours ! **<USER_NAME>** est clairement en mode tryhard. - 💪`,
        `𝐏as un seul oubli en \`<STREAK>\` jours ! **<USER_NAME>** mérite un rappel… mais pas aujourd’hui. - 😌`,
        `\`<STREAK>\` jours alignés pour **<USER_NAME>** ! 𝐓outes les pièces sont en place. - 🧠`,
        `𝐋e streak de **<USER_NAME>** atteint \`<STREAK>\` jours… 𝐎n commence à surveiller ça de près. - 👁️`,
        `\`<STREAK>\` jours consécutifs ! **<USER_NAME>** vient de passer en hyperdrive. - 🌌`,
        `𝐒treak validé ! **<USER_NAME>** entre dans le top des réguliers avec \`<STREAK>\` jours. - 🥇`,
        `𝐎bjectif quotidien réussi depuis \`<STREAK>\` jours pour **<USER_NAME>** ! 𝐓rop propre. - ✨`,
        `𝐋’algorithme confirme : **<USER_NAME>** n’oublie jamais. \`<STREAK>\` jours consécutifs. - 🤖`,
        `𝐔ne nouvelle ligne s’ajoute à la légende : **<USER_NAME>**, \`<STREAK>\` jours de streak. - 📖`,
        `\`<STREAK>\` jours de suite ! **<USER_NAME>** recharge son énergie chaque jour. - 🔋`,
        `𝐋a régularité incarnée : **<USER_NAME>** en est à \`<STREAK>\` jours. - ⭐`,
        `𝐉our après jour, sans faute : **<USER_NAME>** valide \`<STREAK>\` jours consécutifs. - 🗓️`,
        `\`<STREAK>\` jours empilés un par un par **<USER_NAME>**. 𝐑ien ne tombe. - 🧱`,
        `𝐌ention spéciale à **<USER_NAME>** pour ses \`<STREAK>\` jours sans interruption. - 🎖️`,
        `𝐀nnonce officielle : **<USER_NAME>** maintient son streak à \`<STREAK>\` jours ! - 🏛️`,
        `\`<STREAK>\` jours de régularité pure pour **<USER_NAME>**. 𝐂’est beau. - ✨`
    ],

    DailyEmbed: [
        `𝐁ienvenue dans la zone 𝐃aily ! 𝐂'est ici que ton bonus d'𝐗𝐏 t'attend fidèlement chaque jour.\n𝐋e récupère aujourd'hui, mais n'oublie pas de revenir demain ! 𝐈l paraît que les bonus non réclamés se transforment en courgettes... 🍆\n\n𝐀lors, n'attends pas de devoir jardiner, reviens chaque jour !`,
        `𝐀h, toi et ton \`𝐃aily\`, une histoire d'amour qui se prolonge !\n\n𝐓u sais qu'il t'attend depuis **\`23 heures\`** ? Ne brise pas son cœur et reviens demain… sinon, il menace de fuguer chez un autre joueur ! 😆\n𝐈l paraît que les bonus jaloux cherchent toujours de nouveaux fidèles !`,
        `𝐓on bonus quotidien est prêt, avec un message spécial : “𝐉e suis ton fidèle 𝐃aily, et j'attends patiemment tous les jours que tu viennes me récupérer.”\n\n𝐑eviens demain, ne le déçois pas, il a déjà le cœur fragile ! 🥺\n𝐏our lui, chaque jour compte comme une promesse !`,
        `𝐕oici ton \`𝐃aily\` du jour !\nUn conseil : ne laisse jamais un bonus en attente, ils se vexent facilement.\n\n𝐄t surtout, reviens demain, il a déjà prévu votre prochain rendez-vous ! 📅\n◟𝐋es bonus délaissés finissent par s'émanciper...`,
        `𝐋e grand moment est arrivé ! Ton \`𝐃aily\` se tient prêt, fier de te revoir aujourd'hui.\n𝐌ais attention, il aime la régularité : manque un jour, et il pourrait bouder.\n\n𝐕eux-tu vraiment un bonus rancunier ? 🤔\n𝐋e retrouver chaque jour est la meilleure garantie de son amitié !`,
        `𝐂haque jour, ton \`𝐃aily\` t'attend comme un chiot attend son maître.\n\n𝐈l s'illumine quand il te voit apparaître pour le récupérer !\n𝐑eviens demain, sinon il risque de se morfondre jusqu'à ton retour... 🐶\n𝐌ais un retour rapide, et il sera là, tout joyeux !`,
        `𝐑egarde qui est là ! Ton \`𝐃aily\` est de retour, avec plus d'𝐗𝐏 et une touche d'affection.\n\n𝐏romets-lui de revenir demain, il te considère comme son joueur préféré (mais chut, ne le dis pas aux autres !)\n𝐔ne petite visite quotidienne, et il sera fidèle pour toujours ! 🤫`,
        `𝐓on \`𝐃aily\` te fait un grand sourire !\n\n𝐑écupère ton 𝐗𝐏 et n'oublie pas de revenir dans **\`23 heures\`** précises.\n𝐈l note chacune de tes visites avec minutie... 𝐏as de pression, bien sûr ! 📖\n𝐔n jour sans toi, et il en prendrait note, tristement !`,
        `𝐁onne nouvelle ! Ton \`𝐃aily\` est là, et il est bien décidé à te voir chaque jour.\n𝐔n petit rappel : un bonus négligé est un bonus qui risque de se transformer en légende urbaine.\n\n𝐑eviens demain ! 👻\n𝐌ais reviens vite, car il pourrait aussi prendre la grosse tête !`,
        `𝐕oici ton \`𝐃aily\`, fidèle comme toujours !\n\n𝐑emercie-le et assure-toi de ne pas l'oublier demain.\n𝐂ertains bonus rapportent qu'ils se sentent abandonnés après seulement 24h de silence... 😭\n\n𝐔n rendez-vous manqué, et il pourrait commencer à se faire des amis imaginaires !`,
        `𝐓adaa ! Ton \`𝐃aily\` t'attend avec impatience !\n\n𝐂haque jour sans le récupérer lui fait perdre un peu de sa superbe, alors sois régulier et fais-le briller comme jamais ! 🌟\n𝐕eux-tu vraiment risquer de le voir se ternir ?`,
        `𝐋e rendez-vous est sacré ! Ton \`𝐃aily\` est là, prêt à te donner ton 𝐗𝐏 journalier.\n\n𝐌ais ne le laisse pas seul demain, il s'ennuie vite et rêve de fidélité !\n𝐔n vrai romantique, ce bonus… 💞\n𝐑eviens sans faute, ou il pourrait t'écrire des poèmes !`,
        `𝐓on \`𝐃aily\` est arrivé ! Et attention, il prend ton absence très au sérieux.\n\n𝐌anque un jour et il t'écrira une lettre de reproches dignes des meilleures comédies romantiques ! 📜\n𝐎h, la drama queen des bonus...`,
        `𝐂e \`𝐃aily\` était prêt à t'envoyer une alerte si tu tardais encore !\n\n𝐑eviens demain sans faute, il t'offre tout ce qu'il a : 𝐗𝐏, fidélité, et un soupçon de jalousie ! 😜\n𝐔n bonus passionné, qui mérite ton attention quotidienne !`,
        `𝐓u as récupéré ton \`𝐃aily\` ! Fais-en bon usage, et n'oublie pas : le prochain sera disponible dans **\`23 heures\`**, prêt à revivre l'aventure avec toi !\n\n𝐂e bonus a l'âme d'un guerrier ! ⚔️\n𝐑eviens vite, ou il partira à l'aventure sans toi !`,
        `𝐓on \`𝐃aily\` est de retour, fidèle au poste !\n\n𝐌ais attention, il a un avertissement : il ne tolère pas l'oubli. 𝐑eviens demain, sinon il compte bien te donner le goût amer du 𝐗𝐏 manqué ! 😬\n\n𝐋es bonus ont aussi leurs caprices...`,
        `𝐋e voilà, ton \`𝐃aily\`, encore plus enthousiaste que toi pour ce rendez-vous quotidien.\n𝐑eviens demain, il aura rechargé son 𝐗𝐏 et sera prêt pour de nouvelles aventures ! 🎉\n\n𝐀vec toi, il rêve d'un partenariat éternel !`,
        `𝐂e \`𝐃aily\` a traversé les tempêtes du serveur pour arriver jusqu'à toi !\n\n𝐑eviens demain et il te récompensera avec encore plus d'𝐗𝐏.\nCe bonus a le cœur vaillant ! 🌊\n\n𝐕eux-tu vraiment abandonner un bonus aussi courageux ?`,
        `𝐓on \`𝐃aily\` a préparé un discours de bienvenue pour toi, mais il était un peu long, alors voici l'essentiel : merci de ne pas l'oublier demain !\n\n𝐒inon, il risque de se syndiquer... 📢\n𝐔n bonus rebelle ? Mieux vaut ne pas tenter le destin !`,
        `𝐓on \`𝐃aily\` d'aujourd'hui est prêt, et il a préparé une fête secrète pour ton retour demain.\n𝐌ais chut ! 𝐍e le laisse pas sur le carreau, il compte sur ta ponctualité ! 🎈\n\n𝐒euls les fidèles auront droit à cette fête exclusive !`
    ],

    departures: [
    "**<USER_NAME>** a quitté le serveur après \`<TIME>\`. 𝐎n a déjà remplacé sa chaise, pas de souci.",
    "**<USER_NAME>** est parti(e) après \`<TIME>\`. 𝐎n espère qu’il trouvera un Wi-Fi meilleur ailleurs.",
    "**<USER_NAME>** a déserté après \`<TIME>\`. 𝐋e café gratuit n'était visiblement pas suffisant.",
    "**<USER_NAME>** s'est volatilisé après \`<TIME>\`. 𝐏as grave, on garde son mug au cas où.",
    "**<USER_NAME>** est parti(e) en claquant la porte après \`<TIME>\`. 𝐋a porte a survécu, merci de demander.",
    "**<USER_NAME>** a pris ses clics et ses clacs après \`<TIME>\`. 𝐎n récupère les clacs, merci.",
    "**<USER_NAME>** a déserté après \`<TIME>\`. 𝐎n a retrouvé une note : '𝐂'était pas moi, c'était Discord.'",
    "**<USER_NAME>** a sauté du navire après \`<TIME>\`. 𝐎n prépare une bouée au cas où.",
    "**<USER_NAME>** a disparu dans les abysses après \`<TIME>\`. 𝐋es poissons sont sympas, paraît-il.",
    "**<USER_NAME>** est parti(e) chercher du lait après \`<TIME>\`. 𝐎n sait comment ça finit, malheureusement.",
    "**<USER_NAME>** s'est éclipsé(e) après \`<TIME>\`. 𝐎n a cherché partout, même sous la table.",
    "**<USER_NAME>** a disparu dans un vortex temporel après \`<TIME>\`. 𝐑etour prévu en 3023.",
    "**<USER_NAME>** a quitté le serveur après \`<TIME>\`, sûrement pour rejoindre un serveur rival. 𝐓rahison !",
    "**<USER_NAME>** a décidé de se désintégrer après \`<TIME>\`. 𝐑IP, on garde les souvenirs.",
    "**<USER_NAME>** a crié 'Alt+F4' après \`<TIME>\`. 𝐎n espère qu’il reviendra après le redémarrage.",
    "**<USER_NAME>** a quitté le serveur après \`<TIME>\`. 𝐋es derniers mots ? '𝐂'était juste une expérience sociale.'",
    "**<USER_NAME>** a pris un portail magique après \`<TIME>\`. Destination ? 𝐈nconnue.",
    "**<USER_NAME>** a disparu après \`<TIME>\`. 𝐋a CIA nous a demandé de ne pas poser de questions.",
    "**<USER_NAME>** s'est enfui(e) après \`<TIME>\`, en laissant un mot : '𝐉e ne peux plus tolérer RaBByT_Tv.'",
    "**<USER_NAME>** a claqué la porte après \`<TIME>\`, avec une musique dramatique en fond. 𝐄pique.",
    "**<USER_NAME>** a disparu après `<TIME>`. 𝐎n a mis une affiche “𝐑eviens stp”.",
    "**<USER_NAME>** est parti(e) après `<TIME>`. 𝐋e serveur observe une minute de lag en son honneur.",
    "**<USER_NAME>** a quilté le lobby après `<TIME>`. 𝐂’était super… court.",
    "**<USER_NAME>** a pris la fuite après `<TIME>`. 𝐎n a perdu le tracking, trop de split.",
    "**<USER_NAME>** s’est déco après `<TIME>`. 𝐋e fantôme d’Internet l’appelle ailleurs.",
    "**<USER_NAME>** a rage-alt-f4 après `<TIME>`. 𝐏as de crash report, dommage.",
    "**<USER_NAME>** a quitté la game après `<TIME>`. 𝐋e matchmaking le cherchera encore longtemps.",
    "**<USER_NAME>** a mis /leave après `<TIME>`. 𝐎n a sauvegardé sa place… dans nos cœurs (et les logs).",
    "**<USER_NAME>** s’est fait la malle après `<TIME>`. 𝐋e GPS indique “hors zone”.",
    "**<USER_NAME>** a disparu en ninja après `<TIME>`. 𝐏as même une fumigène.",
    "**<USER_NAME>** a pris un TP après `<TIME>`. 𝐃estination inconnue, cooldown 999s.",
    "**<USER_NAME>** a fermé Discord après `<TIME>`. 𝐋a table ronde discutera de ce lore.",
    "**<USER_NAME>** a posé la manette après `<TIME>`. 𝐎n lui garde un slot pour le DLC retour.",
    "**<USER_NAME>** a déserté l’instance après `<TIME>`. 𝐋e boss a récupéré 100% de sa vie.",
    "**<USER_NAME>** est parti(e) en AFK éternel après `<TIME>`. 𝐋e statut est passé en légende.",
    "**<USER_NAME>** a vidé son inventaire après `<TIME>`. 𝐋a poubelle remercie.",
    "**<USER_NAME>** a quitté le vaisseau après `<TIME>`. 𝐏as d’imposteur détecté (cette fois).",
    "**<USER_NAME>** a tiré le câble après `<TIME>`. 𝐋e ping a gagné.",
    "**<USER_NAME>** a perdu la co après `<TIME>`. 𝐋e FAI droppe un rare silence.",
    "**<USER_NAME>** a /quit après `<TIME>`. 𝐋es crédits de fin défilent déjà.",
    "**<USER_NAME>** a quitté le raid après `<TIME>`. 𝐋e loot table s’en remettra.",
    "**<USER_NAME>** a fermé la porte du hub après `<TIME>`. 𝐎n relancera la file d’attente.",
    "**<USER_NAME>** s’est évanoui(e) dans le chat après `<TIME>`. 𝐋e scroll n’a rien vu venir.",
    "**<USER_NAME>** a posé son casque après `<TIME>`. 𝐋a musique s’est mise sur pause dramatique.",
    "**<USER_NAME>** a rendu son badge après `<TIME>`. 𝐋e service RH des émojis prend note.",
    "**<USER_NAME>** a quitté le bus de spawn après `<TIME>`. 𝐋e drop était trop loin.",
    "**<USER_NAME>** a mis fin à la session après `<TIME>`. 𝐋e compteur d’XP pleure doucement.",
    "**<USER_NAME>** a déco proprement après `<TIME>`. 𝐋e serveur dit “merci pour la politesse”.",
    "**<USER_NAME>** a pris le dernier portail après `<TIME>`. 𝐋a mini-map affiche “???”.",
    "**<USER_NAME>** a quitté la guilde après `<TIME>`. 𝐋e drama a fait *pouf* sans saison 2.",
    "**<USER_NAME>** a lâché le mic après `<TIME>`. 𝐅in du concert, rappel un jour peut-être."
],


  };
  
  module.exports = messagesRandom;